### ISSUE TITLE
Finish up AssocGoCamModel.translate()

### ISSUE THREAD

**Issue by dustine32** [geneontology/gocamgen#8]
The code I have already written for AssocGoCamModel looks like it should take a list of ontobio associations and generate a single GO-CAM model, though I seem to have left AssocGoCamModel.translate() in an unfinished state:
```
>>> model.translate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ebertdu/go/gocamgen/gocamgen/gocamgen.py", line 257, in translate
    aspect_triples.append(self.emit(term, ENABLED_BY, annoton.enabled_by))
AttributeError: 'AssocGoCamModel' object has no attribute 'emit'
```
Fixing this method and then `model.write()` should get us a model we can load to Noctua for viewing.

**Comment by dustine32** [comment]
I finished `model.translate()` to the point where it will create annotons from GPAD lines using the same logic from ontobio/rdfgen, though (except for extensions) similar to Paul's rules.

One issue I dealt with was retrieving the aspect from the term since the existing logic (stolen from rdfgen) needed this. Since GPAD doesn't contain this aspect column like GAF does, GPAD could not be translated directly in ontobio/rdfgen. For now, I created a [PR](https://github.com/biolink/ontobio/pull/281) in ontobio for getting the GO aspect from a term. This PR's same code is currently in gocamgen but I'll remove it once the PR is merged and the ontobio package gets updated.

A TODO in rdfgen is to utilize the GPAD relation field, but this can be discussed when further defining translation rules and then implemented either here or in ontobio.
